### ISSUE TITLE
주말인데 좀 쉬세요!!

### ISSUE THREAD

**Issue by WhistlerHusky** [greenfrog82/study#1]
조선임님, 주말인데 좀 쉬세요!!ㅎㅎ

**Comment by greenfrog82** [comment]
의준아, 열심히해서 정상에서 만나자 ㅋㅋㅋ

**Comment by WhistlerHusky** [comment]
조선임님, Github commit message는 영어로 하는게 어때요? 간단하게라도 영어로 하는게 좋을거 같아요ㅎ

**Comment by greenfrog82** [comment]
Ok, I will write commit message in english after commit from now on.
Thank you for your opinion.
